# =============================================================================
# chef/knife.rb — Chef Workstation (knife) configuration
# Used by Jenkins to upload cookbooks and manage nodes
# =============================================================================

current_dir = File.dirname(__FILE__)

# ---- Identity ---------------------------------------------------------------
node_name   'jenkins'
client_key  "#{current_dir}/jenkins.pem"     # generated by Chef Server at org creation

# ---- Chef Server ------------------------------------------------------------
chef_server_url  'http://172.20.0.40/organizations/cicd-demo'
ssl_verify_mode  :verify_none                # self-signed cert in demo

# ---- Cookbook paths ---------------------------------------------------------
cookbook_path    ["#{current_dir}/cookbooks"]

# ---- Logging ----------------------------------------------------------------
log_level     :info
log_location  STDOUT

# ---- Bootstrap defaults -----------------------------------------------------
knife[:ssh_user]     = 'root'
knife[:use_sudo]     = true
knife[:editor]       = '/usr/bin/nano'
knife[:bootstrap_version] = '18'

# ---- Supermarket source (pull community cookbooks) --------------------------
knife[:supermarket_site] = 'http://172.20.0.50'
